package chords;

import java.util.ArrayList;
import java.util.Arrays;

import modes.Mode;
import notes.HarmonicNote;
import scales.Scale;

/**
 * Manages all the chords generated by a scale and a chordStructure. 
 * Permits to pass from one scale to another with modulationChords.
 * 
 * @author Julien ABADJI
 *
 */
public class ChordCollection {
	ArrayList<Chord> harmonizedChords = new ArrayList<Chord>();
	Scale scale;
	/**
	 * Fills the arrayList with harmonized chords of scale
	 * 
	 * @param scale
	 * @param chordStructure
	 */
	public ChordCollection(Scale scale, ArrayList<Integer> chordStructure){
		this.scale = scale;
		Chord chordBuffer;
		Integer degBuffer;
		if(chordStructure == null){
			chordStructure = getDefaultStructure();
		}
		for(int i=1; i<=scale.getNotes().size(); i++){ //Filling the arraylist with the chords, accordingly to chordStructure
			chordBuffer = new Chord();
			for(int j=0; j<chordStructure.size(); j++){
				degBuffer = i+chordStructure.get(j)-1;
				chordBuffer.addNote(scale.getDegree(degBuffer));
			}
			harmonizedChords.add(chordBuffer);
		}
	}
	public ChordCollection(Scale scale){
		this(scale, null);
	}
	
	private ArrayList<Integer >getDefaultStructure(){
		ArrayList<Integer> chordStructure = new ArrayList<Integer>();
		chordStructure.add(1);
		chordStructure.add(3);
		chordStructure.add(5);
		return chordStructure;
	}
	public ArrayList<Chord> getHarmonizedChords(){
		return harmonizedChords;
	}
	public ArrayList<Chord> getHarmonizedChordsFromMode(Mode mode){
		Scale otherScale = new Scale(scale.getFundamental(), mode);
		ChordCollection otherCollection = new ChordCollection(otherScale);
		return otherCollection.getHarmonizedChords();
	}
	public String toString(){
		return harmonizedChords.toString();
	}
	public Scale getScale(){
		return scale;
	}
}

